---
title: "Daynight-Q10"
author: "Colin Wu"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: yes
    toc_float: yes
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
library(dplyr)
library(tidyr)
library(lubridate)
library(ggplot2)
library(suncalc)
library(raster)
library(zoo)
library(leaflet)
library(rvest)
library(rgdal)
#library(StreamMetabolism)
#library(NISTunits)

#Download worldclim data for precip and tmean if necessary, into w10/ folder
precip <- getData("worldclim", path = here::here(), var = "prec", res = 10, download = !file.exists("wc10/prec1.hdr"))
tmean <- getData("worldclim", path = here::here(), var = "tmean", res = 10, download = !file.exists("wc10/tmean1.hdr"))
bio <- getData("worldclim", path = here::here(), var = "bio", res = 10, download = !file.exists("wc10/bio.hdr"))[[c(1,12)]]

library(cosore)
db_info <- csr_database()
results <- list()
```

## Goal 1
```{r goal1, eval=TRUE, echo=FALSE}
print(bio)
print(precip)
rh_dataset_names <- db_info[grep("Rh", db_info$CSR_MSMT_VAR),1][[1]]
for(rhds in rh_dataset_names){
  print(rhds)
}
```

<!--
```{r new-goal1}
rh_dataset_names <- filter(db_info, grepl("Rh", CSR_MSMT_VAR))
rh_dataset_names <- pull(rh_dataset_names, CSR_DATASET)
print(rh_dataset_names)
```
-->

## Goal 2
```{r Goal 2}
results <- list()
for(rhds in rh_dataset_names){
  ds_data <- csr_dataset(rhds)
  ports_table <- ds_data$ports
  Rh_ports <- filter(ports_table, CSR_MSMT_VAR == "Rh")
  results[[rhds]] <- Rh_ports
}

final_results <- bind_rows(results, .id = "Dataset")
print(final_results)
```

## calc_q10 Function
```{r p-value function from https://gettinggeneticsdone.blogspot.com/2011/01/rstats-function-for-extracting-f-test-p.html}
lmp <- function (modelobject) {
  if (class(modelobject) != "lm") stop("Not an object of class 'lm' ")
  f <- summary(modelobject)$fstatistic
  p <- pf(f[1],f[2],f[3],lower.tail=F)
  attributes(p) <- NULL
  return(p)
}
```

```{r Q10 Function}
calc_q10 <- function(temp, resp, out.rm = TRUE){
  positives <- resp > 0 & !is.na(temp) & !is.na(resp)
  resp <- resp[positives]
  temp <- temp[positives]
  
  resp_outliers <- which(resp %in% boxplot(resp, plot=FALSE)$out)
  temp_outliers <- which(temp %in% boxplot(temp, plot=FALSE)$out)
  all_outliers <- unique(c(resp_outliers, temp_outliers))
  
  if(length(all_outliers) > 0L & out.rm){
    temp <- as.vector(temp[-resp_outliers])
    resp <- as.vector(resp[-resp_outliers])
  }
  if(length(resp) < 4){
    return(NA)
  }
  
  lnresp <- log(resp)
  linReg <- lm(lnresp~temp)
  sumReg <- summary(linReg)
  b <- linReg$coefficients[["temp"]]
  q10 <- exp(10*b)
  r_squared = NA
  p_val = NA
  if(!is.infinite(q10) & !is.na(q10)){
    r_squared <- sumReg$r.squared
    p_val <- lmp(linReg)
  }
  return_val <- data.frame(Q10 = q10, R2 = r_squared, P_VALUE = p_val)
  return(return_val)
}
```

```{r Q10 Function Test}
set.seed(2020)
x <- 1:20
y <- 2 ^ (x/10) + rnorm(length(x), sd = .3)
plot(x,y)
cat("The Q10 Value is", calc_q10(x,y)[,1])
```

## Ts Percentage
```{r Ts Percentage}
main_results <- list()
for(rhds in rh_dataset_names){
  ds_data <- csr_dataset(rhds)
  dsd <- ds_data$data
  column_names <- names(dsd)
  temperature_columns <- column_names[grep("^CSR_T(AIR|[0-9]+)", column_names)]
  results <- data.frame(columns = temperature_columns, depth = NA, q10 = NA, n = NA)
  resp <- dsd$CSR_FLUX_CO2
  for(tcol in temperature_columns){
    temp <- dsd[[tcol]]
    results$q10[results$columns == tcol] = calc_q10(temp, resp)[,1]
    results$n[results$columns == tcol] = length(temp[!is.na(temp) & !is.na(resp)])
    depth <- gsub("^CSR_T", "", tcol)
    #Check to see if depth is a number, if it isn't (if it's AIR) then depth is set to -1
    if(!is.na(as.numeric(depth))){
      depth <- as.numeric(depth)
    }else{
      depth <- -1
    }
    results$depth[results$columns == tcol] = depth
  }
  main_results[[rhds]] <- results
}
main_results <- bind_rows(main_results, .id = "Dataset")
print(summary(main_results))
```

## Q10 By Week and Day/Night
```{r by week, cache = TRUE}
week_Q10 <- list()
MA_set <- list()
for(rhds in rh_dataset_names){
  ds_data <- csr_dataset(rhds)
  dsd <- ds_data$data
  ds_desc <- ds_data$description
  ds_ports <- ds_data$ports
  
  column_names <- names(dsd)
  temperature_columns <- column_names[grep("^CSR_T(AIR|[0-9]+)", column_names)]
  rh_ports <- final_results[final_results$Dataset == rhds, ][[2]]
  rs_ports <- ds_ports[ds_ports$CSR_MSMT_VAR == "Rs",][[1]]
  
  date <- as.Date(dsd$CSR_TIMESTAMP_END)
  lon <- ds_desc$CSR_LONGITUDE
  lat <- ds_desc$CSR_LATITUDE
  timezone <- attr(dsd$CSR_TIMESTAMP_END, "tzone")
  
  sunrise_set <- getSunlightTimes(date, lat, lon, keep = c("sunrise", "sunset"), tz = timezone)
  #sunrise_set <- sunrise.set(lat, lon, date)
  sunrise <- sunrise_set[["sunrise"]]
  sunset <- sunrise_set[["sunset"]]
  
  #Extract Mean Annual Data
  MA_row <- data.frame(LON = lon, LAT = lat)
  
  # MAP data that matches the srdb coordinates
  raster::extract(precip, MA_row[1:2]) -> precip_coords
  apply(precip_coords, 1, sum) -> MA_row$MAP
  
  # The same for MAT
  raster::extract(tmean, MA_row[1:2]) -> tmean_vals
  apply(tmean_vals, 1, mean)/10 -> MA_row$MAT
  
  #MA_row <- cbind.data.frame(MA_row, raster::extract(bio, MA_row[1:2]))
  MA_set[[rhds]] <- MA_row
  
  dsd %>% 
    mutate(DAY_NIGHT = case_when(
      sunrise < CSR_TIMESTAMP_BEGIN & CSR_TIMESTAMP_BEGIN < sunset ~ "day",
      TRUE ~ "night"), 
      Rs_Rh = case_when(
        CSR_PORT %in% rh_ports ~ "Rh", 
        CSR_PORT %in% rs_ports ~ "Rs",
        TRUE ~ "other")) %>%
    filter(!is.na(CSR_FLUX_CO2), CSR_FLUX_CO2 > 0, Rs_Rh != "other") %>%
    mutate(WOY = week(CSR_TIMESTAMP_END),
           MONTH = month(CSR_TIMESTAMP_END),
           YEAR = year(CSR_TIMESTAMP_END),
           DAY_NIGHT = factor(DAY_NIGHT),
           Rs_Rh = factor(Rs_Rh)) ->
    dsd
  
  for(tcol in temperature_columns){
    dsd$temp <- dsd[[tcol]]
    depth <- gsub("^CSR_T", "", tcol)
    # Check to see if depth is a number, if it isn't (if it's AIR) then depth is set to -1
    if(!is.na(as.numeric(depth))){
      depth <- as.numeric(depth)
    } else {
      depth <- -1
    }
    dsd %>% 
      group_by(YEAR, MONTH, DAY_NIGHT, Rs_Rh) %>% 
      summarize(DATASET = rhds, 
                DEPTH = depth, 
                Q10 = calc_q10(temp, CSR_FLUX_CO2, out.rm = TRUE),
                TEMP = mean(temp, na.rm=TRUE), 
                RESP = mean(CSR_FLUX_CO2, na.rm = TRUE),
                N = n()) %>% 
      unpack(cols = Q10) %>%
      mutate(MON_YEAR = paste(YEAR, MONTH, 15, sep = "/"), MON_YEAR = as.Date(MON_YEAR)) -> 
      week_Q10[[paste(rhds, depth, sep="_")]]
  }
}
#as.yearmon(paste(YEAR, MONTH), "%Y %m")
#paste(YEAR, MONTH, 1, sep = "/")
MA_set <- bind_rows(MA_set, .id = "DATASET")

bind_rows(week_Q10, .id = "ID") %>% 
  filter(!is.na(Q10), is.finite(Q10)) %>% 
  dplyr::select(DATASET, YEAR:MONTH, MON_YEAR, DAY_NIGHT, Rs_Rh, DEPTH:RESP, N) %>% 
  arrange(DATASET, DEPTH, YEAR, MONTH) %>%
  left_join(MA_set, by = "DATASET") -> 
  week_Q10



print(week_Q10)
summary(week_Q10)
print(MA_set)
```

## Sunset/Sunrise Calculation Test
```{r, eval=FALSE}
#daytime <- function(lat, long, doy){
#  lat <- NISTdegTOradian(lat)
#  long <- NISTdegTOradian(long)
#  frac_yr = 2 * pi/365 * (doy - 1 + (hr-12)/24)
#  eqtime = 229.18*(0.000075+0.001868*cos(frac_yr)-0.032077*sin(frac_yr)-0.014615*cos(2*frac_yr)-0.040849*sin(2*frac_yr))
#  decl =  0.006918-0.399912*cos(frac_yr)+0.070257*sin(frac_yr)-0.006758*cos(2*frac_yr)+0.000907*sin(2*frac_yr)-0.002697*cos(3*frac_yr)+0.00148*sin(3*frac_yr)
#  ha = acos(cos(NISTdegTOradian(90.833))/(cos(lat)*cos(decl))-tan(lat)*tan(decl))
#  sunrise=720-4*(long+ha)-eqtime
#  sunset=720-4*(long-ha)-eqtime
#}
lat <- 39.110940
lon <- -77.171990
date <- "2020/07/29"
date2 <- as.Date(date)
timez = Sys.timezone()
sunrise_set = sunrise.set(lat, lon, date2 + 1, timezone=timez)
print(sunrise_set)
sunset_rise = getSunlightTimes(date2, lat, lon, keep = c("sunrise", "sunset"), tz = timez)
print(sunset_rise)
print(sunset_rise[["sunrise"]])
print(sunset_rise[["sunset"]])
print(sunrise_set)
sunrise = sunrise_set[[1]]
sunset = sunrise_set[[2]]
class(sunrise)
print(sunrise < sunset)
format(sunrise)
```

## Graphing Results {.tabset}
```{r, fig.height=6, eval = FALSE}
p <- ggplot(week_Q10, aes(WOY, Q10, color = DAY_NIGHT, group = paste(YEAR, DAY_NIGHT))) + 
  geom_line(na.rm = TRUE) +
  ylim(c(0, 12)) + 
  facet_wrap(~ID+DEPTH)
print(p)
```

### Distributions
```{r Distr, fig.width=10}
a <- ggplot(week_Q10, aes(x = R2)) + geom_histogram(color= "black", fill = "white") + labs(title = "R2 Distribution") + geom_vline(aes(xintercept = median(R2)), linetype="dashed", color="red") + geom_text(aes(label = paste("Median =", round(median(R2), digits=3))), x = 0.15, y = 400, size = 3)
ggsave("R2 Distribution.png", a)
a2 <- ggplot(week_Q10, aes(x = Q10)) + geom_histogram(color= "black", fill = "white") + xlim(0, 12.5) + labs(title = "Q10 Distribution") + stat_bin(geom="text", aes(label=..count..), size = 2, vjust = -1) + geom_vline(aes(xintercept=median(Q10)), linetype="dashed") + geom_text(aes(label = paste("Median =", round(median(Q10), digits=3))), x = 5, y = 150, size = 3) + geom_text(aes(label = paste("Mean =", round(mean(Q10), digits=3))), x = 5, y = 200, size = 3)
ggsave("Q10 Distribution.png", a2)
a3 <- week_Q10 %>% group_by(Rs_Rh) %>% summarise(medianval = median(Q10)) %>% right_join(week_Q10, by = "Rs_Rh") %>% ggplot(aes(x = Q10)) + geom_histogram(color= "black", fill = "white") + labs(title = "Q10 Distribution by Rs/Rh") + xlim(0, 12.5) + facet_wrap(~Rs_Rh) + stat_bin(geom="text", aes(label=..count..), size = 2, vjust = -1) + geom_vline(aes(xintercept = medianval), color = "red", linetype="dashed", size = 1) + geom_text(aes(label = paste("Median =", round(medianval, digits=3))), x = 5, y = 150, size = 3)
ggsave("Rh-Rs Q10 Distribution.png", a3)
b <- ggplot(week_Q10, aes(x = R2, fill=DAY_NIGHT)) + geom_histogram(position = "dodge2") + facet_wrap(~DATASET) + labs(title = "R2 By Dataset")
ggsave("R2 By Dataset.png", b)
c <- ggplot(week_Q10, aes(x = Q10, fill=DAY_NIGHT)) + geom_histogram(position = "dodge2") + xlim(0, 12.5) + facet_wrap(~DATASET) + labs(title = "Q10 By Dataset")
ggsave("Q10 By Dataset.png", c)

print(a)
print(a2)
print(a3)
print(b)
print(c)
```

### Tiles
```{r tiles}
week_Q10 %>% group_by(DATASET, MONTH) %>%
  summarize(Q10 = mean(Q10)) %>% 
  left_join(MA_set, by = "DATASET") -> 
  month_Q10

week_Q10 %>% group_by(MONTH, YEAR) %>%
  summarize(Q10 = mean(Q10)) -> 
  monthyear_Q10

d <- ggplot(month_Q10, aes(x = MONTH, y = DATASET, fill = Q10)) + geom_tile() + lims(fill = c(0, 12.5))
ggsave("tile1.png", d)
d2 <- ggplot(monthyear_Q10, aes(x = MONTH, y = YEAR, fill = Q10)) + geom_tile() + lims(fill = c(0, 12.5))
ggsave("tile2.png", d2)
print(d)
print(d2)
```

### Rs and Rh Day/Night Variation
```{r, fig.width=10}
Rs_depths_list <- levels(as.factor(week_Q10$DEPTH[week_Q10$Rs_Rh == "Rs"]))
Rh_depths_list <- levels(as.factor(week_Q10$DEPTH[week_Q10$Rs_Rh == "Rh"]))
Shared_depths_list <- intersect(Rs_depths_list, Rh_depths_list)

for(depth in Shared_depths_list){
  Rs_table <- week_Q10 %>% 
    filter(Rs_Rh == "Rs", DEPTH == as.numeric(depth))
 
   # Do a paired t-test; is daytime Q10 > nighttime Q10?
  Rs_table %>% 
    dplyr::select(DATASET, MON_YEAR, DAY_NIGHT, Q10) %>% 
    spread(DAY_NIGHT, Q10) %>% 
    group_by(DATASET) %>% 
    summarise(t_test_p = t.test(day, night, paired = TRUE)$p.value) -> p_table #%>% 
    #left_join(Rs_table, by = "DATASET") -> Rs_table
    
  print(p_table)
  
  p <- ggplot(Rs_table, aes(MON_YEAR, Q10, color = DAY_NIGHT, group = paste(YEAR, DAY_NIGHT))) +
    geom_point() + ylim(0,12.5) + 
    facet_wrap(~DATASET, scales = "free_x") + 
    labs(title = paste("Rs Variation by Day/Night at depth", depth)) #+ geom_text(stat="identity", position="identity", aes(label = paste("p-value =", round(t_test_p, digits=3))), y = 9, size = 3)
  print(p)
ggsave(paste0(depth, "Rs.png"), p)
  
  p <- week_Q10 %>% 
    filter(Rs_Rh == "Rh", DEPTH == as.numeric(depth), DATASET %in% Rs_table$DATASET) %>% 
    ggplot(aes(MON_YEAR, Q10, color = DAY_NIGHT, group = paste(YEAR, DAY_NIGHT))) +
    geom_point() + ylim(0,12.5) + 
    facet_wrap(~DATASET, scales = "free_x") + 
    labs(title = paste("Rh Variation by Day/Night at depth", depth)) +
    theme(strip.background = element_blank(),
          strip.text.x = element_text(size = 10))
  print(p)
  
  p <- week_Q10 %>% 
    filter(DEPTH == as.numeric(depth), DATASET %in% Rs_table$DATASET) %>% 
    ggplot(aes(MON_YEAR, Q10, color = DAY_NIGHT, group = paste(YEAR, DAY_NIGHT))) + 
    geom_point() + 
    ylim(0,12.5) + 
    facet_grid(Rs_Rh~DATASET, scales = "free_x") + 
    labs(title = paste("Rh and Rs Variation by Day/Night at depth", depth)) + 
    theme( strip.background = element_blank(),
           strip.text.x = element_text(size = 10))
  print(p)
}
```

### Day and Night Variation by Rs/Rh
```{r, warning=FALSE, fig.width=10}
for(depth in Shared_depths_list){
  Rs_table <- week_Q10 %>% filter(DAY_NIGHT == "day", DEPTH == as.numeric(depth))
  print(ggplot(Rs_table, aes(MON_YEAR, Q10, color = Rs_Rh, group = paste(YEAR, DAY_NIGHT))) + geom_point() + ylim(0,12.5) + facet_wrap(~DATASET, scales = "free_x") + labs(title = paste("Day Variation by Rs/Rh at depth", depth)))
  print(ggplot(week_Q10 %>% filter(DAY_NIGHT == "night", DEPTH == as.numeric(depth), DATASET %in% Rs_table$DATASET), aes(MON_YEAR, Q10, color = Rs_Rh, group = paste(YEAR, DAY_NIGHT))) + geom_point() + ylim(0,12.5) + facet_wrap(~DATASET, scales = "free_x") + labs(title = paste("Night Variation by Rs/Rh at depth", depth)) + 
          theme(
            strip.background = element_blank(),
            strip.text.x = element_text(size = 10)
          ))
  print(ggplot(week_Q10 %>% filter(DEPTH == as.numeric(depth), DATASET %in% Rs_table$DATASET), aes(MON_YEAR, Q10, color = Rs_Rh, group = paste(YEAR, DAY_NIGHT))) + geom_point() + ylim(0,12.5) + facet_grid(DAY_NIGHT~DATASET, scales = "free_x") + labs(title = paste("Day and Night Variation by Rs/Rh at depth", depth)) + 
          theme(
            strip.background = element_blank(),
            strip.text.x = element_text(size = 10)
          ))
}
```

### Other Graphs
```{r, fig.height=10, fig.width=10}
Rs_table <- week_Q10 %>% filter(Rs_Rh == "Rs", DEPTH == 5)
x2 <- ggplot(Rs_table, aes(MON_YEAR, Q10, color = DAY_NIGHT, group = paste(YEAR, DAY_NIGHT))) + geom_point() + ylim(0,12.5) + facet_wrap(~DATASET, scales = "free_x") + labs(title = paste("Rs Variation by Day/Night at depth", 5))
ggsave("Rs5.png", x2)
Rh_table <- week_Q10 %>% filter(Rs_Rh == "Rh", DEPTH == 5)
x3 <- ggplot(Rh_table, aes(MON_YEAR, Q10, color = DAY_NIGHT, group = paste(YEAR, DAY_NIGHT))) + geom_point() + ylim(0,12.5) + facet_wrap(~DATASET, scales = "free_x") + labs(title = paste("Rh Variation by Day/Night at depth", 5))
ggsave("Rh5.png", x3)
ggsave("Rs5.png", x2)

print(ggplot(week_Q10 %>% filter(DAY_NIGHT == "day"), aes(MON_YEAR, Q10, color = Rs_Rh, group = paste(YEAR, DAY_NIGHT))) + geom_point() + ylim(0,12.5) + facet_wrap(~DATASET+DEPTH, scales = "free_x") + labs(title = "Day Variation by Rs/Rh"))

print(ggplot(month_Q10, aes(MAT, MAP, color = Q10)) + geom_jitter() + lims(color = c(0, 12.5)))

# Boxplots of Q10 versus MAP and MAT
ggplot(month_Q10, aes(MAP, Q10)) + 
  geom_boxplot(aes(color = DATASET)) + 
  ylim(c(0, 12.5)) + 
  scale_color_discrete(guide = FALSE) +
  xlab("MAP (mm)") +
  geom_smooth(data = filter(month_Q10, MAP < 1500), 
              method = "lm", linetype = 2, color = "black")
ggsave("map_boxplot.png", width = 8, height = 5)

ggplot(month_Q10, aes(MAT, Q10)) + 
  geom_boxplot(aes(color = DATASET)) + 
  ylim(c(0, 12.5)) + 
  xlab(expression(MAT~( degree*C))) +
  scale_color_discrete(guide = FALSE) +
  geom_smooth(data = filter(month_Q10, MAT < 6), 
              method = "lm", linetype = 2, color = "black") +
  geom_smooth(data = filter(month_Q10, MAT >= 5), 
              method = "lm", linetype = 2, color = "black")
ggsave("mat_boxplot.png", width = 8, height = 5)
```

```{r Site Map}
coord_table <- db_info %>% filter(CSR_DATASET %in% rh_dataset_names) %>% dplyr::select(CSR_DATASET, CSR_LONGITUDE, CSR_LATITUDE)
coordinates(coord_table) <- ~CSR_LONGITUDE + CSR_LATITUDE
coordinates(db_info) <- ~CSR_LONGITUDE + CSR_LATITUDE
lflt <- addMarkers(leaflet(coord_table), label = coord_table$CSR_DATASET)
addTiles(lflt)
lflt <- addMarkers(leaflet(db_info), label = db_info$CSR_DATASET)
addTiles(lflt)
```

#Moisture Data

```{r SMOS Functions}
SMOSfiles <- function(date){
  #scrape https://gimms.gsfc.nasa.gov/SMOS/jbolten/FAS/L03/ for file names
  read_html("https://gimms.gsfc.nasa.gov/SMOS/jbolten/FAS/L03/") %>%
  html_nodes(".indexcolname") %>% html_text() -> filenames
  
  fileDate <- as.Date(date)
  #create vector of all possible file name dates
  probDate <- c(fileDate-1, fileDate, fileDate+1)
  probDate %>% lapply(as.Date) %>% lapply(format, "%Y%m%d") -> probDate
  
  #make sure that the earliest possible date is the first date in the file name
  probDate[1] <- paste0(probDate[1], "_")
  #make suer that the latest possible date is the last date in the file name
  probDate[3] <- paste0("_",probDate[3])
  
  patterns <- paste(probDate, collapse="|")
  matchfiles <- filenames[grep(patterns, filenames)]
  fileurls <- paste0("https://gimms.gsfc.nasa.gov/SMOS/jbolten/FAS/L03/", matchfiles)
  #download.file(fileurls, "L03")
  return(matchfiles)
}

SMOSdata <- function(date, lon, lat){
  SMOSfile <- SMOSfiles(date)
  SMOSfile %>% lapply(raster) -> SMOSfile
  extent(SMOSfile[[1]]) <- extent(-180, 180, -60, 90)
  extent(SMOSfile[[2]]) <- extent(-180, 180, -60, 90)
  lapply(SMOSfile, raster::extract, data.frame(x=lon, y=lat)) ->
  moisture
  return(moisture)
}
  
SMOSfiles("2012/12/18")
SMOSfiles("2012/12/17")
SMOSfiles("2012/12/16")
SMOSdata("2010/1/10", -150.1, 60.1)
```

