---
title: "Extracting Moisture"
output:
 html_document:
    toc: yes
    toc_float: yes
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rNOMADS)
#NOTE: wgrib2, which is required to run the ReadGrib() function, is really hard 
#to download on Windows. I have attached the necessary files for a precompiled 
#version to this repo. Just copy the directory location to PATH to have it work.
library(raster)
library(rgdal)
library(tidyr)
```

```{r Tests, eval=FALSE}
#just playing around with rNOMADS
NOMADSRealTimeList("grib")
```

```{r Moisture}
#Extract Sample Moisture data from NASA-USDA Global Soil Moisture Data
# <- ReadGrib("20100110_20100112.as1.grib", file.type="grib2", variables = "", levels ="")
#Note to Self: levels are regions of the atmosphere, surface of the earth, or subsurface
#variables are the type of data (ex: Temperature)

moisture <- raster("L03/20100110_20100112.as1.grib")

#newmoisture <- projectRaster(moisture, crs = "+proj=longlat")
#print(newmoisture)
#extent(moisture) <- extent(-180, 180, -60, 90)
#projection(moisture) <- "+proj=longlat +no_defs +init=epsg:4326"
#moisture <- projectRaster(moisture, crs="+proj=longlat +datum=WGS84 +no_defs")
crs(moisture) <- "+proj=stere +datum=WGS84 +ellps=WGS84"
plot(moisture)
maps::map(add = T)
lat <- c(-80:80)
long <- c(-170, 70)
xy <- crossing(long, lat)  # crosses the Sahara so should be easy to see if correct
sp <- SpatialPoints(xy, proj4string = CRS("+proj=longlat +datum=WGS84 +no_defs"))
print(sp)
raster::extract(moisture, sp, df=TRUE)

#testlocal <- raster::extract(moisture, data.frame(x= 50.1234, y=60.1))
#print(testlocal)
#helpful page: https://gis.stackexchange.com/questions/299954/unknown-projection-of-grib-file
```


